#-------------------------------
# General Site Settings
title: Victoria Richard 
logo: logo_bk.svg # You can add own logo.
description: 


#-------------------------------
# Welcome info
welcome:
  oneliner: Conflict Resolution and Facilitation Specialist 
  about: My mission, as a trained Facilitator, is to engage as a neutral party with anyone finding themselves in the middle of a conflict.  
  

# Author Settings
author:
  name: Victoria Richard 
  image: victoria.jpg
  say-hello: Hello, I'm Victoria. 
  bio: My name is Victoria, and I am a conflict resolution specialist and facilitator. I help individuals resolve interpersonal conflicts wherever in life, they may be experiencing it, and I facilitate the process of change within companies. My degree in Human Relations and experience working in various team settings, combined with a hunger for understanding interpersonal relationships has led me to this career. We often fear conflict and change, as it is uncomfortable and can be unpleasant if approached and perceived in the wrong way. However conflict and change are important obstacles to overcome when trying to achieve growth. In order to overcome these obstacles, I enter the situation as a neutral party to help resolve the conflict.
 



#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: thegoatsmilkshake # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
