#-------------------------------
# General Site Settings
title: Victoria Richard 
logo: logo_bk.svg # You can add own logo.
description: 


#-------------------------------
# Welcome info
welcome:
  oneliner: Conflict Resolution and Facilitation Specialist 
  about: My mission, as a trained Facilitator, is to engage as a neutral party with anyone finding themselves in the middle of a conflict.  
  

# Author Settings
author:
  name: Victoria Richard 
  image: victoria.jpg
  say-hello: Hello, I'm Victoria. 
  bio: My mission, as a trained Facilitator, is to engage as a neutral party with anyone finding themselves in the middle of a conflict.  Together with a B.A. in Human Relations from Concodria University, and professional certifications in bla bla bla. I have a unique range of skills to help guide your conflicts to a satisfactory resolution, while maintaining the health of your relationships. Above all, I believe in helping to foster constructive environments... 



#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: thegoatsmilkshake # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
